# Generated by Django 5.2.12 on 2026-04-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_modelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cor',
            old_name='descricao',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='descricao',
        ),
        migrations.AddField(
            model_name='modelo',
            name='categoria',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='marca',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='nome',
            field=models.CharField(default='sem', max_length=80),
            preserve_default=False,
        ),
    ]
