# Generated by Django 5.2.12 on 2026-04-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_veiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name_plural': 'Cores'},
        ),
    ]
